---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudnative-pg
  labels:
    cnpg.io/reload: ""
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: ops-store
  target:
    name: postgres-secrets
  data:
    - secretKey: username # Not sure if currently used
      remoteRef:
        key: POSTGRES_SECRETS
        property: POSTGRES_SUPER_USER
    - secretKey: password
      remoteRef:
        key: POSTGRES_SECRETS
        property: POSTGRES_SUPER_PASS
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: POSTGRES_SECRETS
        property: AWS_ACCESS_KEY_ID
    - secretKey: AWS_ACCESS_SECRET
      remoteRef:
        key: POSTGRES_SECRETS
        property: AWS_ACCESS_SECRET