---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudnative-pg
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: ops-store
  target:
    name: postgres-secrets
  data:
    - secretKey: PG_SUPER_USER # Not sure if currently used
      remoteRef:
        key: POSTGRES_SECRETS
        property: POSTGRES_SUPER_USER
    - secretKey: PG_SUPER_PASS
      remoteRef:
        key: POSTGRES_SECRETS
        property: POSTGRES_SUPER_USER
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: POSTGRES_SECRETS
        property: AWS_ACCESS_KEY_ID
    - secretKey: AWS_ACCESS_SECRET
      remoteRef:
        key: POSTGRES_SECRETS
        property: AWS_ACCESS_SECRET