---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app hasura-graphql
  namespace: flux-system
spec:
  targetNamespace: hasura
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apps/hasura/hasura/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m0s
  retryInterval: 1m
  timeout: 5m
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app hasura-migrations
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  path: ./kubernetes/apps/hasura/hasura/migrations
  targetNamespace: hasura
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 30m0s
  timeout: 5m
  retryInterval: 1m
  prune: true
  wait: true
  force: true # When an immutable field is changed, flux will recreate the resource. Beneficial because we'll be updating the image tag.