apiVersion: batch/v1
kind: Job
metadata:
  name: hasura-migrations
  labels:
    app.kubernetes.io/name: hasura-migrations
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: hasura-migrations
          image: ghcr.io/ronin-cg/hasura-migrations:52a1739
          env:
            - name: HASURA_GRAPHQL_ENDPOINT
              value: "http://hasura-graphql-engine.hasura.svc.cluster.local:8080"
            - name: HASURA_GRAPHQL_ADMIN_SECRET
              valueFrom:
                secretKeyRef:
                  name: hasura-secrets
                  key: HASURA_GRAPHQL_ADMIN_SECRET
      imagePullSecrets:
        - name: ghcr-login-secret
  backoffLimit: 4