apiVersion: batch/v1
kind: Job
metadata:
  name: hasura-migrations
  labels:
    app.kubernetes.io/name: hasura-migrations
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: hasura-migrations
          image: ghcr.io/ronin-cg/hasura-migrations:4398cdd
          command: ["migrate", "apply", "--database-url", "postgres://hasura:hasura@hasura-postgres:5432/hasura"]
          env:
            - name: HASURA_GRAPHQL_ENDPOINT
              value: "http://hasura-graphql-engine.hasura.svc.cluster.local:8080"
            - name: HASURA_GRAPHQL_ADMIN_SECRET
              valueFrom:
                secretKeyRef:
                  name: hasura-secrets
                  key: admin-secret
  backoffLimit: 4