---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hasura-configs
data:
  HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
  GRAPHQL_ENDPOINT: "http://hasura-graphql-engine.hasura.svc.cluster.local:8080/v1/graphql"