---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hasura-external-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: ops-store
  target:
    name: hasura-secrets
  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: HASURA_SECRETS
        property: POSTGRES_USER
    - secretKey: POSTGRES_DB
      remoteRef:
        key: HASURA_SECRETS
        property: POSTGRES_DB
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: HASURA_SECRETS
        property: POSTGRES_PASSWORD
    - secretKey: HASURA_GRAPHQL_METADATA_DATABASE_URL
      remoteRef:
        key: HASURA_SECRETS
        property: HASURA_GRAPHQL_METADATA_DATABASE_URL
    - secretKey: HASURA_GRAPHQL_ADMIN_SECRET
      remoteRef:
        key: HASURA_SECRETS
        property: HASURA_GRAPHQL_ADMIN_SECRET

---
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hasura-db-conns-external-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: ops-store
  target:
    name: hasura-db-connections
  data:
    - secretKey: FORECAST_DB_URI
      remoteRef:
        key: HASURA_DATABASE_CONNECTIONS
        property: FORECAST_DB_URI
    
    - secretKey: TENANTS_DB_URI
      remoteRef:
        key: HASURA_DATABASE_CONNECTIONS
        property: TENANTS_DB_URI
    
    - secretKey: INVENTORY_DB_URI
      remoteRef:
        key: HASURA_DATABASE_CONNECTIONS
        property: INVENTORY_DB_URI
    