---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: hasura-external-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: ops-store
  target:
    name: hasura-secrets
  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: HASURA_SECRETS
        property: POSTGRES_USER
    - secretKey: POSTGRES_DB
      remoteRef:
        key: HASURA_SECRETS
        property: POSTGRES_DB
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: HASURA_SECRETS
        property: POSTGRES_PASSWORD
    - secretKey: HASURA_GRAPHQL_METADATA_DATABASE_URL
      remoteRef:
        key: HASURA_SECRETS
        property: HASURA_GRAPHQL_METADATA_DATABASE_URL
    - secretKey: HASURA_GRAPHQL_ADMIN_SECRET
      remoteRef:
        key: HASURA_SECRETS
        property: HASURA_GRAPHQL_ADMIN_SECRET

    