---
apiVersion: v1
kind: Service
metadata:
  name: hasura-graphql-engine
  annotations:
  labels:
    app: hasura-graphql-engine
spec:
  selector:
    app: hasura-graphql-engine
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hasura-graphql-engine
  labels:
    app: hasura-graphql-engine
spec:
  selector:
    matchLabels:
      app: hasura-graphql-engine
  replicas: 1
  template:
    metadata:
      annotations:
      labels:
        app: hasura-graphql-engine
    spec:
      containers:
        - name: graphql-engine
          image: hasura/graphql-engine:v2.38.1
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          readinessProbe:
            failureThreshold: 5
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          env:
            - name: HASURA_GRAPHQL_ENABLE_CONSOLE
              valueFrom:
                configMapKeyRef:
                  key: HASURA_GRAPHQL_ENABLE_CONSOLE
                  name: hasura-configs
            - name: HASURA_GRAPHQL_CORS_DOMAIN
              value: "*"
            # Self-hosted control plane configurations for Hasura Enterprise classic
            - name: HASURA_GRAPHQL_METADATA_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  key: HASURA_GRAPHQL_METADATA_DATABASE_URL
                  name: hasura-secrets
            - name: HASURA_GRAPHQL_ADMIN_SECRET
              valueFrom:
                secretKeyRef:
                  key: HASURA_GRAPHQL_ADMIN_SECRET
                  name: hasura-secrets
            - name: POSTGRES_DB_FORECAST_RW
              valueFrom:
                secretKeyRef:
                  key: FORECAST_DB_URI
                  name: hasura-db-connections
            - name: POSTGRES_DB_TENANTS_RW
              valueFrom:
                secretKeyRef:
                  key: TENANTS_DB_URI
                  name: hasura-db-connections
            - name: POSTGRES_DB_INVENTORY_RW
              valueFrom:
                secretKeyRef:
                  key: INVENTORY_DB_URI
                  name: hasura-db-connections