---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ronin-ui-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: ops-store
  target:
    name: ronin-ui-secrets
  data:
    - secretKey: AMAZON_APP_ID
      remoteRef:
        key: AMAZON_SECRETS
        property: AMAZON_APP_ID