---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: supertokens-core
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: ops-store
  target:
    name: supertokens-core-secrets
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: POSTGRES_SECRETS
        property: AWS_ACCESS_KEY_ID
    - secretKey: AWS_ACCESS_SECRET
      remoteRef:
        key: POSTGRES_SECRETS
        property: AWS_ACCESS_SECRET
    - secretKey: API_KEYS
      remoteRef:
        key: SUPERTOKEN_SECRETS
        property: API_KEYS