---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: supertokens-backend
  labels:
    app.kubernetes.io/name: supertokens
    app.kubernetes.io/instance: supertokens-backend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: supertokens
      app.kubernetes.io/instance: supertokens-backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: supertokens
        app.kubernetes.io/instance: supertokens-backend
    spec:
      containers:
      - name: supertokens-backend
        image: ghcr.io/ronin-cg/auth-backend:39c3251
        imagePullPolicy: IfNotPresent
        env:
          - name: ST_CORE_URL
            value: http://supertokens-core.supertokens.svc.cluster.local:3567
          - name: ST_WEBSITE_URL
            value: https://app-dev.${SECRET_DOMAIN}
          - name: ST_BACKEND_API_URL
            value: https://auth-dev.${SECRET_DOMAIN}
          - name: ST_API_KEY
            valueFrom:
              secretKeyRef:
                name: supertokens-backend-secrets
                key: API_KEY
          - name: ST_COOKIE_DOMAIN
            value: .${SECRET_DOMAIN}
          - name: GRAPHQL_ENDPOINT
            value: https://graphql-dev.${SECRET_DOMAIN}
          - name: GRAPHQL_ADMIN_KEY
            valueFrom:
              secretKeyRef:
                name: supertokens-backend-secrets
                key: GRAPHQL_ADMIN_KEY
          - name: AMAZON_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: supertokens-backend-secrets
                key: AMAZON_CLIENT_ID
          - name: AMAZON_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: supertokens-backend-secrets
                key: AMAZON_CLIENT_SECRET
          - name: AMAZON_REDIRECT_URI
            value: https://app-dev.${SECRET_DOMAIN}
          - name: SMTP_HOST
            valueFrom:
              configMapKeyRef:
                name: supertoken-backend-configs
                key: SMTP_HOST
          - name: SMTP_PORT
            valueFrom:
              configMapKeyRef:
                name: supertoken-backend-configs
                key: SMTP_PORT
          - name: SMTP_FROM_EMAIL
            valueFrom:
              configMapKeyRef:
                name: supertoken-backend-configs
                key: SMTP_FROM_EMAIL
          - name: SMTP_FROM_NAME
            valueFrom:
              configMapKeyRef:
                name: supertoken-backend-configs
                key: SMTP_FROM_NAME
          - name: SMTP_SECURE
            valueFrom:
              configMapKeyRef:
                name: supertoken-backend-configs
                key: SMTP_SECURE
          - name: SMTP_USER
            valueFrom:
              secretKeyRef:
                name: supertokens-backend-secrets
                key: SMTP_USER
          - name: SMTP_PASSWORD
            valueFrom:
              secretKeyRef:
                name: supertokens-backend-secrets
                key: SMTP_PASSWORD
          # AWS Env Vars
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: supertokens-backend-secrets
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: supertokens-backend-secrets
                key: AWS_SECRET_ACCESS_KEY
          - name: AWS_REGION
            valueFrom:
              configMapKeyRef:
                name: supertoken-backend-configs
                key: AWS_REGION
          # Inventory DB Env Vars
          - name: INVENTORY_DB_HOST
            valueFrom:
              configMapKeyRef:
                name: supertoken-backend-configs
                key: INVENTORY_DB_HOST
          - name: INVENTORY_DB_PORT
            valueFrom:
              configMapKeyRef:
                name: supertoken-backend-configs
                key: INVENTORY_DB_PORT
          - name: INVENTORY_DB_NAME
            valueFrom:
              configMapKeyRef:
                name: supertoken-backend-configs
                key: INVENTORY_DB_NAME
          - name: INVENTORY_DB_USER
            valueFrom:
              configMapKeyRef:
                name: supertoken-backend-configs
                key: INVENTORY_DB_USER
          - name: INVENTORY_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: supertokens-backend-secrets
                key: INVENTORY_DB_PASSWORD
          # Ducklake DB Env Vars
          - name: DUCKLAKE_DB_HOST
            valueFrom:
              configMapKeyRef:
                name: supertoken-backend-configs
                key: DUCKLAKE_DB_HOST
          - name: DUCKLAKE_DB_PORT
            valueFrom:
              configMapKeyRef:
                name: supertoken-backend-configs
                key: DUCKLAKE_DB_PORT
          - name: DUCKLAKE_DB_NAME
            valueFrom:
              configMapKeyRef:
                name: supertoken-backend-configs
                key: DUCKLAKE_DB_NAME
          - name: DUCKLAKE_DB_USER
            valueFrom:
              configMapKeyRef:
                name: supertoken-backend-configs
                key: DUCKLAKE_DB_USER
          - name: DUCKLAKE_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: supertokens-backend-secrets
                key: DUCKLAKE_DB_PASSWORD
      imagePullSecrets:
        - name: ghcr-login-secret
---
apiVersion: v1
kind: Service
metadata:
  name: auth-backend
  annotations:
  labels:
    app.kubernetes.io/name: auth-backend
spec:
  selector:
    app.kubernetes.io/name: supertokens
    app.kubernetes.io/instance: supertokens-backend
  ports:
  - name: http
    port: 3001
    targetPort: 3001
  type: ClusterIP
