---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: supertokens-backend
  labels:
    app.kubernetes.io/name: supertokens
    app.kubernetes.io/instance: supertokens-backend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: supertokens
      app.kubernetes.io/instance: supertokens-backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: supertokens
        app.kubernetes.io/instance: supertokens-backend
    spec:
      containers:
      - name: supertokens-backend
        image: ghcr.io/ronin-cg/auth-backend:47f0363
        imagePullPolicy: IfNotPresent
        env:
          - name: ST_CORE_URL
            value: http://supertokens-core.supertokens.svc.cluster.local:3567
          - name: ST_WEBSITE_URL
            value: https://app-dev.${SECRET_DOMAIN}
          - name: ST_BACKEND_API_URL
            value: https://auth-dev.${SECRET_DOMAIN}
          - name: ST_API_KEY
            valueFrom:
              secretKeyRef:
                name: supertokens-backend-secrets
                key: API_KEY
          - name: GRAPHQL_ENDPOINT
            value: https://graphql-dev.${SECRET_DOMAIN}
          - name: GRAPHQL_ADMIN_KEY
            valueFrom:
              secretKeyRef:
                name: supertokens-backend-secrets
                key: GRAPHQL_ADMIN_KEY
          - name: AMAZON_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: supertokens-backend-secrets
                key: AMAZON_CLIENT_ID
          - name: AMAZON_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: supertokens-backend-secrets
                key: AMAZON_CLIENT_SECRET
          - name: AMAZON_REDIRECT_URI
            value: https://app-dev.${SECRET_DOMAIN}
      imagePullSecrets:
        - name: ghcr-login-secret
---
apiVersion: v1
kind: Service
metadata:
  name: auth-backend
  annotations:
  labels:
    app.kubernetes.io/name: auth-backend
spec:
  selector:
    app.kubernetes.io/name: supertokens
    app.kubernetes.io/instance: supertokens-backend
  ports:
  - name: http
    port: 3001
    targetPort: 3001
  type: ClusterIP
