---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: supertokens-backend
  labels:
    app.kubernetes.io/name: supertokens
    app.kubernetes.io/instance: supertokens-backend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: supertokens
      app.kubernetes.io/instance: supertokens-backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: supertokens
        app.kubernetes.io/instance: supertokens-backend
    spec:
      containers:
      - name: supertokens-backend
        image: ghcr.io/ronin-cg/auth-backend:9757b5d
        imagePullPolicy: IfNotPresent
        env:
          - name: ST_CORE_URL
            value: http://supertokens-core.supertokens.svc.cluster.local:3567
          # - name: ST_BACKEND_API_URL
          #   value: auth.dev.${SECRET_DOMAIN}
          - name: ST_WEBSITE_URL
            value: http://app.dev.${SECRET_DOMAIN}
      imagePullSecrets:
        - name: ghcr-login-secret

---
apiVersion: v1
kind: Service
metadata:
  name: auth-backend
  annotations:
  labels:
    app.kubernetes.io/name: auth-backend
spec:
  selector:
    app.kubernetes.io/name: supertokens
    app.kubernetes.io/instance: supertokens-backend
  ports:
  - name: http
    port: 3001
    targetPort: 3001
  type: ClusterIP
