---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: supertokens-backend
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: ops-store
  target:
    name: supertokens-backend-secrets
  data:
    - secretKey: API_KEY
      remoteRef:
        key: SUPERTOKEN_SECRETS
        property: API_KEY_BACKEND
    - secretKey: GRAPHQL_ADMIN_KEY
      remoteRef:
        key: HASURA_SECRETS
        property: HASURA_GRAPHQL_ADMIN_SECRET
    - secretKey: AMAZON_CLIENT_ID
      remoteRef:
        key: AMAZON_SECRETS
        property: AMAZON_CLIENT_ID
    - secretKey: AMAZON_CLIENT_SECRET
      remoteRef:
        key: AMAZON_SECRETS
        property: AMAZON_CLIENT_SECRET
    - secretKey: SMTP_USER
      remoteRef:
        key: RESEND_SECRETS
        property: SMTP_USER
    - secretKey: SMTP_PASSWORD
      remoteRef:
        key: RESEND_SECRETS
        property: SMTP_PASSWORD
    - secretKey: INVENTORY_DB_PASSWORD
      remoteRef:
        key: POSTGRES_SECRETS
        property: INVENTORY_DB_PASSWORD
    - secretKey: DUCKLAKE_DB_PASSWORD
      remoteRef:
        key: POSTGRES_SECRETS
        property: DUCKLAKE_DB_PASSWORD