---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: supertokens-backend
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: ops-store
  target:
    name: supertokens-backend-secrets
  data:
    - secretKey: API_KEY
      remoteRef:
        key: SUPERTOKEN_SECRETS
        property: API_KEY_BACKEND