---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: auth-backend
  labels:
    app.kubernetes.io/name: auth-backend
  annotations:
    external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"

spec:
  ingressClassName: internal
  rules:
  - host: auth.dev.${SECRET_DOMAIN}
    http:
      paths:
      - backend:
          service:
            name: auth-backend
            port:
              number: 3001
        pathType: Prefix
        path: /