apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:coSL6N+J9mD7DC8iHUG3p4OgOt5ZJtKxMT3PMTT1zTByBmgg,iv:SQxIMmrJf5Z3ixk3Xrs6tl3r5RQ7vXw9QNag19rQEUw=,tag:RnM1PgQ7HsdKBfXsIo0Ebg==,type:str]
    credentials.json: ENC[AES256_GCM,data:OvOwyqku0RS/xH4iUG6GibV/w2dsC/YCCz8tCX+DVce8UiwkBihESD8PPdFp8MRuruiZwRYODMmksgTe07BIpX9ibKhpa2W7/LKZ9hUyRKo+woGvsHjtngy5Jg+k5jIqPC1kyJrxEcii82HqhvAlcqYq0I3UFdi7OGydmF6g3Oy6eq2pfpb7nKa54flDz6gj3n+uDBPST9t4zdCQnmYwsreq7CUCdeuNxLsp6UAyvQ==,iv:YpXzwaYfyrssUXGrVx3aqpqnFx5EqH43rcosL4ls2bo=,tag:OPxPqdF3hvrIUJCs+p75IA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18qqcd4mkmu67sfrynf4jft9a3qqe67guvlt9kr0s3eatygh8zqhq80jqmv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLajZ0Vy9lVWwxVDdCZ2Rw
            VG8ySytqL1IybWRESVBJQ2gzY2pUSERrVEFNCm15Z2hDOUxiNTFjQy8rQlpYUzg1
            eklXTnJyWHdlbGZWc0ZQQmtCdnRkUUEKLS0tIFNueFhaNWtkVVRPaHJzT3BiSnQr
            OG94SDRXamNQTUkwRHVnYnFyRUlmc3cKPf8P6mQWMtgRsxZ9MEBd6o3NzdYtcaAu
            GO2Wd5N0O/zJL5JVPNIJKtLYx+XDgcfw17D5Vo4imD1rl2AEdRf3Lw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-01T12:56:44Z"
    mac: ENC[AES256_GCM,data:TV9CYyvp2HxLQrwcCfHMTw6cM1c4e1N4xj01zyX8AAHIZlLGUnmDRvlYYwXFpemBBRRJLGW1PaCGVJXMnXe6I2cPoBgvmir7n/9dX3dJgyyZ0qBMo8A04JeDmsGJdvVjpPB3nKSxa4+lhiiwqOL0kUjKenrFFwSt/02NP99IMdU=,iv:ZHk00Za6GNKJm54VXzInPGdEwe4Yb+17GAXzd2B5Wzs=,tag:qPO7K0oxtNuRtj+35R+0zQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
