---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: onepassword-connect
spec:
  interval: 5m
  timeout: 3m0s
  chart:
    spec:
      chart: connect
      version: 1.15.0
      sourceRef:
        kind: HelmRepository
        name: 1password
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    connect:
      credentialsName: onepassword-credentials
      credentialsKey: 1password-credentials.json