apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 30m
  timeout: 15m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 58.3.3
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      retries: 3
      strategy: rollback
  # https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml
  values:
    crds:
      enabled: true
    cleanPrometheusOperatorObjectNames: true
    prometheus:
      ingress:
        enabled: true
        ingressClassName: internal
        pathType: Prefix
        hosts:
          - "prometheus.${SECRET_DOMAIN}"

      prometheusSpec:
        retention: 24h
        resources:
          requests:
            cpu: 200m
            memory: 200Mi
    nodeExporter:
      enabled: true
    grafana:
      ingress:
        enabled: true
        ingressClassName: internal
        pathType: Prefix
        hosts:
        - "grafana.${SECRET_DOMAIN}"