apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:Doi5uvbNU4zbRqI6bSPgPHoOaxJn7n7OBhdAF5bjGgNJA/nf1889yZJRZwxVSE0weEvbtBbAgYaPq0W6HlqBgbJJmS2VOVU4TZAjN2KbDKYQbVpykUjgwoELRkSohQ==,iv:CU0+xxvnyn16vifrNla5Kf3exthyEtEnI8UcOAZvS6w=,tag:3E0EG/P1hqt0cnWQOMFPyg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18qqcd4mkmu67sfrynf4jft9a3qqe67guvlt9kr0s3eatygh8zqhq80jqmv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKVnB3MTBwWm5RTFFiS0kv
            bEwyZURmSlF6RHJlZE84UHVRdE9DSjluTFUwCmh5cU4xbDg2Y2xBWWMvT3ptcWY1
            L2IxdUttYTcxaFJVSTBTM0M3RGVwZmcKLS0tIG1GbXZnMUxCMjkxcXQ4Q00wT1o4
            bW5oSDU2SXdYNlRtUGlUR0xESUVDUFUKZRFTIhva+LjDkAlSwEDq9jGfjf5oExRa
            14MIVjqdyP6Ab8avqFcH//tSfZvRjRHYGiqgkYBepVZIiICcr8PGtg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-30T16:38:30Z"
    mac: ENC[AES256_GCM,data:xR0UTW5NNCEGX7NqdYalXnqp08rRf/LqUKijfAlzY5smjh7rTAhztQtyupGwqNkl8xhac4D+yphFeJe9dPqfNOXMl1TDoYQ9S86LBfHdBqG/ZvaQpQ0XZHwHqC5lIo2J427lWfynCOWTmZje9K+FvTmhtH9bLgDWAq0Egv3Hq8s=,iv:97JrEsiDWg4Ht6jM8D43n4Qsicjqp1Lsy9DpMytHOWI=,tag:sOe6ZvwGAyUnValRVdG4AA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
