apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:GPI6rLQswlZe9IJVkuJQ4AUa9QNyCXPtJbFVQKo4UhOVHTk5c9W6CjiX7hcAzPqzaBgoqrvj9tjcciBjpouVhT1FZNuYbge0cczQ34Iqw3bveSTOLpAikLlzwl83HQ==,iv:4Vt+Zuz0QsBJTpZYjWEDr3YNVRa15hzaxVrALGrskVM=,tag:y978uw6tpX9+uRrN/Z7bBA==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:wdcA27CsUSOl/SoYWQ==,iv:R3RzrMu0R/Rlc2zNCSYdDWf4gLStxR7bl62x1x3NDp4=,tag:d0y9rNl+zQIJG5bwrDp29g==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:eIpHlv1iXiMWSdmYkJZOXTjqVw==,iv:1ItaQ/LBurDoMVkKoY+N5QjsM7XOGncNWKitLU5MIc4=,tag:kiYFTltmxytllsvIT3CvAQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:/XvNncDzx+d2+1gnKGWSHBSD9flsn5RnhsE2kKmWhRU5LD8x,iv:cdiYzjCZwXPhXj9Rxr/5mrjerdgoVsV3SlZrhmi0DXA=,tag:MPC2If1tSLNqiNUfATmSqQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18qqcd4mkmu67sfrynf4jft9a3qqe67guvlt9kr0s3eatygh8zqhq80jqmv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwTUthR0g4Z2c4RUNsVTRk
            OXFnRVJNVld4amthaXNnNFZPVVNabmdCOFY0CjFQcXBlSFplTUczYlJPZ1M3NGdP
            WTArK1lBZDZPM3RTcUMvVUtucFdYWTAKLS0tIGl1ZWNnQmlIK1lPMU9sTmRlOGR6
            M0hOZFhna1hTUHdUV2ZyM09Ya1Y3WkUKlsO7jqb9yz5mw9UjaCzLcoxO7Qq+5k2T
            2sR/fiaiBT1HdeLgbXhAAJ7AOkfBfo7VEFA5afhbIMuzPDOyNil0cA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-01T12:56:45Z"
    mac: ENC[AES256_GCM,data:oRIyCzeR9uQ2sRHMGaGwU+Ix7OOV4LE1Qym4mBu/2SvuE1aa2quMYwD6X/waK2+gK54PyWMcWB3WJo8O/MblLsCZzee7jKktL6F1GOXskrwfiANLifq39t1JslbDUIyE5hKMbTvgSn/LbC1nICTowM0ISLToUOmj7eedPTNGa3U=,iv:4T6f/tNPBpRg0l8gVorBNT6nRaRIHzo6Pro7vwk4G30=,tag:QkSlKmchfDA2q0RM5hTNjw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
