apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:UWpxJ8WW5zM+g3MDDjS/nPTwtQWCD/DbdTEytql8pjSXc7Ru45RMLt2ZJWiH6LvQW30EroLcbIWB2qT1WbEmtZiK+2hlkmiCduVkM+jKLeuImAqOzU/9j0JakADXvg==,iv:eUV6kZWu+nAEbFknnZz2ffMBdZZOViyI5o0ULrcsFxk=,tag:H/U9svQV54UmBwnD8XzLmA==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:wrRM0UhIDQi2aXcw9g==,iv:50sOxXAgRIGXWdXhY2vER/X90oMODcdIJNJe+gsCYh0=,tag:gI6cnq2LI/cIo3zLbrug3w==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:tLnrXIUG1eqDx2NaqMxLEnOtKg==,iv:LxfDsD/Nj7bH4WG8PYJH7CfbLtyB+LiPUWTAEO7R4zc=,tag:u0NMEh+d7D1ZiNDunxtccw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:coXt96QqaTkbNOFSbYWo5ZnYbOnHrfRvV5Ormx95hOAVX6kh,iv:orc80L3uyizJwh8XBDtLro8AZ01xxLtFKuYZohaVae4=,tag:CmJxuQwwTAkEhiWx+lpx0A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18qqcd4mkmu67sfrynf4jft9a3qqe67guvlt9kr0s3eatygh8zqhq80jqmv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4UTNNU1VuMlFaRTBsTFlV
            TmFMVnlKbUc0YUFMSkttZTNqcTNrUFlVNENnCkRITmZaOEM0czNJdnJBZjlyMFBz
            YjNwSElheTNaMjNaek1BWkN3VzJra2MKLS0tIE9ta2RjVkpxcXVqaU0vSnNRa0lB
            R0N2TndMU3ByTHZWZGlERnpYYncxOWsKolluqBZ7EMzYUKx3zJ51nGYwGltHi2lh
            fHzma2vpsfNVlBQ+MP8moLVzya4PA6eXyeYGSoEkedX7aUHYxaVJbA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-01T12:11:23Z"
    mac: ENC[AES256_GCM,data:7gv7PV3W0z8pqVbwSk1APFJTg4/+B7fwDoGEaHkLEaYSV/TLmyPD3rJ6fVUI8fTrtfQDLzB0LcCIxYkApHZigoaspzYZqQoFfQBUfkOofiZgR2u5SJmUyIIw3yQDHd7k1DoqkSr1ve5JaGdRx7eBGmebf8LCMFF4k2MF/HcE4Dc=,iv:DTqiOisSZf+m+i9x2HY+clZcOavXDK9KUUknlnuSb4c=,tag:8GKr8a66rwEPRjCdBTSvCg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
