apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:rYz5W8hMFg/pvFigTCTl5WoU+6XzquVtL2UZ6JMHdMI=,iv:ogNAWRzVUFY1hMCKiwFGftC7Mj7/YpylMI8kJP2tPTE=,tag:0LorFFgh+K6cAh9JFi5xaA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18qqcd4mkmu67sfrynf4jft9a3qqe67guvlt9kr0s3eatygh8zqhq80jqmv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1RHdwN1ErVERaTjZ2ZFhp
            bUM2amczR0hNeWx1dTRMdnYzWjQ4bG9vSlFJCmc3UUQwZVNkS3RWbEFNWHE3T3U2
            SGlXZW5SWE1jbHNlSExBaGxPR1lSRzgKLS0tICtlU1NqblpZQmtuNVlsMVVMcmN2
            UGJLVEEzKzk2NTJiVjBhK0FBNGh3SU0KxulkhHA6de/EC8JfWQno3CdROSmSvmNw
            BbttZUpAVfgE8/Sb7yf2rICgOQ8xeWvRAENO/pTLDpWvtcEyv+qHAA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-30T16:38:30Z"
    mac: ENC[AES256_GCM,data:uq37y3TrB1rHRcM/AIhM44GygG1BMaztmeWKGEZJ0REmXYWOZgt9ws99gLvXGtYU44N3Ya4d4/DUwJHcYZ4sHc415hiQYpoBarUpPiog5epW3cOAfySRXUIrBAUt+yE8OZYysq+gJLKCKLdv5RMYqYwPaK7XrIYcx0auocPAmro=,iv:ZsPdjyXW6zPhrca3actRW91/YIVIT1BLh8ZimM8KSEk=,tag:Afn3BtjO+m1Ue2kTEkLlPA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
