apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:XP9iHsjMuaUlsGFuzLf+/mEmfPOcV55XJaszFM+rhpJXDW0pK/Vxrw==,iv:tyZfiOlorlIVy4/Zp9gdclJPDmYGh0Ukm5VSSG6Z0zA=,tag:og+4KQ5Z/j/9CzOwjjelKw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18qqcd4mkmu67sfrynf4jft9a3qqe67guvlt9kr0s3eatygh8zqhq80jqmv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqVmpxdHJVclMzV3B3MFhq
            MFk0MGJ4ZU5INzk4M1JveDl0RXpodWxUcVZRCk9MLzB6YUI2VXFVMkxGSWpWNGMz
            alpyRVF0WVg5SkhFYnp5ZWpWZUg3ZmMKLS0tIHNreDg2V1BXQ3lOZnR1KzJaVEdM
            TkVHUlZYWG8yeE1kbG05ODllejZZcjgKwucZMeRCKL8ALMgwRT1YkPM+OK+udZ/Z
            7N9FGuGQZMcujLpQWt8O8MSBembM7YxV5Wuh6g5ItRMe1g/DJKX88w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-01T11:21:06Z"
    mac: ENC[AES256_GCM,data:3yREhS2HBzfHs1GrF0vVxN8+WLHtgsHoF0oNod7V9dnRFGiJTN04O3KUjBy45C64Y8t64VjWLUMzZwQf/xGRSKaU+8wbizlnIgDPxfBYKU8tqWRAm0Fy/ij7J5gmhtZgl/s68shHDlxjy6CeY1zRa2rkPkMyZKQHA7v7/L4f3gc=,iv:VoJVLvaUi1Qe2lfEnJDklgzpmOBYdz5zrjmLAzgQLXg=,tag:Gan0q/7RIc2wLKmBc3WM1g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
