---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ghcr-login-secret
  namespace: flux-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: ops-store
  target:
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ .secretjson | toString }}"
    name: ghcr-login-secret
    creationPolicy: Owner
  data:
  - secretKey: secretjson
    remoteRef:
      key: GHCR_CREDENTIALS
      property: ghcr.json