---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: supertokens-backend
  namespace: flux-system
spec:
  image: ghcr.io/ronin-cg/auth-backend
  interval: 1h
  provider: generic
  secretRef: 
    name: ghcr-login-secret